### ISSUE TITLE
I cannot find any difference using AjaxFlow over traditional wp_ajax. Any idea?

### ISSUE THREAD

**Issue by nirajkvinit** [EkAndreas/ajaxflow#2]
My JS Code
```
jQuery.post($ajax_flow_url+'fn_import_to_tally_ajax', submit_data, function(response)
        {
```
Here $ajax_flow_url is http://adore/pbb/ajaxflow/

PHP Code 
```
add_action('ajaxflow_fn_import_to_tally_ajax', 'fn_import_to_tally_ajax');
```

**Comment by EkAndreas** [comment]
When using your own ajax-handler it is possible to load wp different and only choose the functions you need.
There are a lot of info on the web handling the issue. Search for “SHORTINIT".

Med vänlig hälsning, Andreas Ek, 070-3032203

**Comment by nirajkvinit** [comment]
Thank you!
